### ISSUE TITLE
ImportError: No module named 'mass'

### ISSUE THREAD

**Issue by shrx** [luisnaranjo733/periodic#1]
If I want to import periodic with `import periodic`, I get an error:

```
Traceback (most recent call last):
  File "/home/marting/PycharmProjects/simple/3d_test.py", line 4, in <module>
    import periodic
  File "/usr/local/lib/python3.4/dist-packages/periodic/__init__.py", line 1, in <module>
    import mass
ImportError: No module named 'mass'
```

I installed periodic with `sudo pip3 install periodic`.

**Comment by kalvdans** [comment]
This bug will be fixed by pull request #2.

**Comment by Pyxidatol-C** [comment]
The distribution on https://pypi.python.org/pypi/periodic still has the import problem:
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from periodic import element
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yjj/anaconda3/lib/python3.6/site-packages/periodic/__init__.py", line 1, in <module>
    import mass
ModuleNotFoundError: No module named 'mass'
```

**Comment by mdommett** [comment]
I am also seeing this problem, is there a fix that could be worked on ? Thanks

**Comment by 42force** [comment]
Yes, was there an answer for this specific issue?

**Comment by u-gajera** [comment]
Still same problem

**Comment by Br0Fi** [comment]
In case more people run into this problem and just want a quick fix for themselves, I recommend the following:
Go to `/usr/lib/python3.8/site-packages/periodic` (or wherever the package manager put your python and periodic installation) and edit the `__init__.py` to reflect the changes made in the following pull request:
https://github.com/luisnaranjo733/periodic/pull/2/commits/29b131da1f46dd642cae74a4a2731089412196df

**Comment by ravivemagiri** [comment]
Error: File "/Users/*******/anaconda3/lib/python3.6/site-packages/periodic/__init__.py", line 1, in <module>
open the path which is shown in console with __init__.py
example pico "/Users/******/*********/............./__init__.py"

open this path using pico and vim editor and update the two lines in the file to below two lines

from . import mass
from .table import *

IT worked for me.

**Comment by sazidism** [comment]
Facing the same problem

**Comment by sudarshanDudhe** [comment]
found the issue... its with the imports in __init__.py in the package. Made changes to the __init__.py in stored or installed package by adding .(dot) before importing and it worked.   
new __init__.py ==>
`
from . import mass
from .table import *
`

**Comment by Gerardwx** [comment]
I pushed the updated code to pypi as _periodic2023_ https://pypi.org/project/periodic2023/
